import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ColorblindProvider } from "@/components/colorblind-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { StructuredData } from "@/components/structured-data";
import {
  GoogleAnalytics,
  GoogleAnalyticsIdentity,
} from "@/components/analytics/google-analytics";
import { GoogleAdSense } from "@/components/analytics/google-adsense";
import { GeoCapture } from "@/components/analytics/geo-capture";
import { SidebarStateProvider } from "@/components/sidebar-state-provider";
import { PwaInstallPrompt } from "@/components/pwa-install-prompt";
import {
  SIDEBAR_COOKIE_NAME,
  parseSidebarCookie,
} from "@/lib/sidebar-cookie";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://www.pokemonpalette.com"),
  title:
    "PokémonPalette - Extract Color Palettes from Pokémon Sprites | Color Generator Tool",
  description:
    "Generate beautiful color palettes from your favorite Pokémon sprites. Extract dominant colors, create custom palettes, and discover the perfect color schemes for your design projects. Browse all 1000+ Pokémon with shiny variants.",
  keywords: [
    "pokemon",
    "color palette",
    "color extraction",
    "design tools",
    "pokemon colors",
    "sprite colors",
    "color generator",
    "palette generator",
    "pokemon sprites",
    "shiny pokemon",
    "color picker",
    "hex colors",
    "rgb colors",
    "hsl colors",
    "web design",
    "graphic design",
    "pokemon art",
    "color schemes",
    "pokemon palette",
    "digital art tools",
  ],
  authors: [
    {
      name: "Yassen Shopov",
      url: "https://github.com/yassenshopov",
    },
  ],
  creator: "Yassen Shopov",
  publisher: "PokémonPalette",

  // OpenGraph metadata for social media sharing.
  // The actual image is generated by src/app/opengraph-image.tsx (Next.js
  // file convention), which auto-populates openGraph.images. Do not set
  // `images` here - explicit values override the file convention.
  openGraph: {
    title: "PokémonPalette - Extract Color Palettes from Pokémon Sprites",
    description:
      "Generate beautiful color palettes from your favorite Pokémon sprites. Extract dominant colors and create custom palettes for your design projects.",
    url: "https://www.pokemonpalette.com",
    siteName: "PokémonPalette",
    locale: "en_US",
    type: "website",
  },

  // Twitter Card metadata. Image is generated by src/app/twitter-image.tsx.
  twitter: {
    card: "summary_large_image",
    title: "PokémonPalette - Extract Color Palettes from Pokémon Sprites",
    description:
      "Generate beautiful color palettes from your favorite Pokémon sprites. Extract dominant colors and create custom palettes for design projects.",
    creator: "@yassenshopov",
  },

  // Additional metadata
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Favicon and icons are generated by src/app/icon.tsx and
  // src/app/apple-icon.tsx (Next.js file conventions). Do not set `icons`
  // here - explicit values override the file convention.

  manifest: "/site.webmanifest",

  // Canonical URL
  alternates: {
    canonical: "https://www.pokemonpalette.com",
  },

  // Verification for search engines (optional)
  // verification: {
  //   google: "Add your Google Search Console verification code",
  //   yandex: "Add your Yandex verification code if needed",
  //   yahoo: "Add your Yahoo verification code if needed",
  // },

  // Pinterest Rich Pin + domain verification.
  // "pinterest-rich-pin" tells the Rich Pin validator to parse OG tags.
  // "p:domain_verify" is the code Pinterest issued when claiming
  // pokemonpalette.com via Business > Settings > Claimed Accounts.
  other: {
    "pinterest-rich-pin": "true",
    "p:domain_verify": "b7e19d937190b7aaaa61a3f272fb2293",
  },
};

// Separate viewport export (required since Next 14 — previously bundled into
// `metadata`). Theme color matches the CSS tokens used by `body` so the
// mobile browser chrome blends into the page in both light and dark mode.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Do NOT set maximumScale or userScalable: false — disabling zoom is an
  // accessibility failure per WCAG 1.4.4.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  colorScheme: "light dark",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if Clerk keys are available
  const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  // Read the persisted sidebar state from the cookie so the layout renders
  // with the correct width on first paint, avoiding a layout shift after
  // hydration. Defaults to collapsed when no cookie has been set yet.
  const cookieStore = await cookies();
  const sidebarCollapsed = parseSidebarCookie(
    cookieStore.get(SIDEBAR_COOKIE_NAME)?.value
  );

  // Wrap children with ClerkProvider only if keys are available. The
  // GA4 identity tracker also lives inside this branch — it depends on
  // `useUser()` and would crash without a ClerkProvider above it.
  const content = publishableKey ? (
    <ClerkProvider publishableKey={publishableKey}>
      {children}
      <GoogleAnalyticsIdentity />
      <GeoCapture />
    </ClerkProvider>
  ) : (
    children
  );

  const ga4Id = process.env.NEXT_PUBLIC_GA4_ID;
  const adsenseClientId = process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased`}
      >
        {/* Skip link — visible only when focused. Keyboard users tab here
            first and can jump past the header to the page content. Pages
            should render their primary content inside `<main id="main">`. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-background focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        >
          Skip to main content
        </a>
        <StructuredData />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // Suppress the cross-fade transition during the very first
          // dark/light swap so users with the "dark" preference don't
          // see a one-frame light flash on hydration. The bespoke
          // radial view-transition in `lib/theme-transition.ts` still
          // runs for explicit user toggles; this only suppresses the
          // automatic transition that next-themes injects.
          disableTransitionOnChange
        >
          <ColorblindProvider>
            <SidebarStateProvider defaultCollapsed={sidebarCollapsed}>
              {content}
            </SidebarStateProvider>
            <Toaster position="top-center" />
            {/* PWA install prompt — silently waits for `beforeinstallprompt`
                from the browser, then renders a dismissable banner. Only
                effective on Chrome/Edge/Brave; iOS uses a different flow. */}
            <PwaInstallPrompt />
          </ColorblindProvider>
        </ThemeProvider>
        <GoogleAnalytics measurementId={ga4Id} />
        <GoogleAdSense clientId={adsenseClientId} />
      </body>
    </html>
  );
}
